apiVersion: apps/v1
kind: Deployment
metadata:
  name: pohodnik-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pohodnik
  template:
    metadata:
      labels:
        app: pohodnik
    spec:
      containers:
        - image: pockar/pohodnik:latest
          name: pohodnik
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://cornelius.db.elephantsql.com:5432/mfyrfjbx
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: mfyrfjbx
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              #value:
              valueFrom: #use Kubernetes secret for storing the password
               # secretKeyRef: 
                ## key: #to be added
          ports:
            - containerPort: 8082
              name: server
          livenessProbe:
            httpGet:
              path: /health/live
              port: server
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health/ready
              port: server
            initialDelaySeconds: 5
            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: pohodnik
spec:
  type: ClusterIP
  ports:
    - port: 8082
      protocol: TCP
      targetPort: server
  selector:
    app: pohodnik
