kumuluzee:
  name: pohodnik-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8082
    http:
      port: 8082
  datasources:
    - jndi-name: jdbc/pohodnikDS
      connection-url: jdbc:postgresql://localhost:5432/pohodnik
      username: dbuser
      password: postgres
      pool:
        max-size: 4
  openapi-mp:
    extension:
      enabled: true
    ui:
      path: /api/ui
      specification-path: /api/spec
      config:
        url: /api/spec
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/pohodnikDS
  metrics:
    web-instrumentation:
      - name: pohodnik-endpoint
        url-pattern: /v1/users/*
rest-properties:
  broken: false
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="Pohodnik">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="70b30c4c-a54e-476a-a5ea-42d916818926-ls.logit.io"
                                    port="21053" protocol="udp">
                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="info" />
                                        <AppenderRef ref="logstash" level="trace" />
                                    </Root>
                                </Loggers>
                            </Configuration>'

